stage1_config: experiments_IITDCogent/configs/stage1_iitdcogent.yaml
stage2_config: experiments_IITDCogent/configs/stage2_iitdcogent_convnext.yaml
data_prep_config: configs/data_prep.yaml

class_ids:
  patterned: 0
  normal: 1
  clear: 2

data:
  test_dir: /research/iprobe-farmanif/2tage_convnext_IJCB/data_IITD_Cogent_ready/iris_contact/val
