class_ids:
  normal: 0
  clear: 1

seg_classes:
  - pupil
  - iris
  - outer_arc

roi_classes:
  - pupil
  - iris
  - outer_arc

data:
  train_dir: /research/iprobe-farmanif/2tage_convnext_IJCB/data_IITD_Cogent_ready/iris_contact/train
  val_dir:   /research/iprobe-farmanif/2tage_convnext_IJCB/data_IITD_Cogent_ready/iris_contact/val
  test_dir:  /research/iprobe-farmanif/2tage_convnext_IJCB/data_IITD_Cogent_ready/iris_contact/val

backbone: convnext
convnext_type: convnext_base
attn_stage: 2

attn_type:    spatial
num_heads:    4
se_reduction: 16

epochs:          80
inp_dim:         [480, 640]
batch_size:      8
num_workers:     4
dropout_prob:    0.4

optimizer:       AdamW
weight_decay:    1e-4
criterion:       CrossEntropyLoss
label_smoothing: 0.05

lr_scheduler:
  type:      cosine
  lr:        0.0002
  eta_min:   1e-6
  step_size: 15
  gamma:     0.1
